### PR TITLE
Test + fix an additional failure case

### PR DESCRIPTION
**Pull request by bradenmacdonald**
This is a follow up to #112 - it turns out I missed another failure mode (if you delete that last step, while the student is on that step).

### CODE REVIEW

**Comment by Kelketek** [comment]
@bradenmacdonald The Review Grade button is always visible for me on this branch. Any idea why? I didn't see it in @smarnach 's PR earlier when I checked it, did you?

**Comment by Kelketek** [comment]
@bradenmacdonald On this branch, when I delete the last node and revisit, I'm dropped onto the last question, prompted to answer it, rather than at the review grade page. This forces me to re-answer that question, but not the first one, and uses up an attempt.

**Comment by bradenmacdonald** [comment]
@Kelketek: I notice the review grade thing - seems to happen when max_attempts is unlimited. Not sure what introduced that yet. If the fix is simple, I'll include it on this branch.

Thanks for catching that issue - it wasn't caught by my test because it only happens if you have an HTML node in there somewhere - it turns out that mentoring v1 includes HTML nodes in the "step" index :-/

**Comment by bradenmacdonald** [comment]
@Kelketek: Turns out the review grade button issue has been there since March - it was introduced via one of the commits in 3290d1a66178f1472d2bc2dbd4f33859bb635f4c. Luckily the fix is easy: I pushed a fix for it and modified my new test so that it checks for that as well. It turns out one of us had already made the same fix to Problem Builder at some point.

**Comment by smarnach** [comment]
@bradenmacdonald Deleting questions might still lead to questionable behaviour.  Assume we have five questions, named A, B, C, D, E.  A student answers A and B and goes away.  If they get back to the course, the next question shown to them will be C.  If now the course author deletes question A in the meantime, they will be shown question D instead, with no way of getting back to question C, which they never answered.  When they finish all questions, the statistics will show e.g. 3 questions answered correctly, 0 partially correctly, 0 incorrectly with a score of 75 %, which seems weird.

The behaviour could be made at least a bit saner by consequently using question names instead of step numbers, but then renaming questions will have weird results.

I don't know whether it is in scope to fix this behaviour, or whether we only want it to stop crashing.  If the goal is only the latter, :+1:.

**Comment by bradenmacdonald** [comment]
@smarnach  Those are excellent points. I'm not sure of how we could address that - like you said, even switching to using names would only change, not solve, the problem. For now I think we just need to focus on making the block not crash, and hope that authors are not going to be deleting blocks in a live course. @antoviaque What do you think?

**Comment by antoviaque** [comment]
@bradenmacdonald Yup, exactly - the intent is just to ensure the block doesn't crash. The authors know that they should be doing this in the first place, and will end up will buggy behavior when they change a block on which students have already answered.

**Comment by Kelketek** [comment]
@bradenmacdonald I'm still having issues with this.

I pulled your latest changes, and then did the following:

1. Created a new Mentoring Xblock instance.
2. Set it to assessment.
3. Answered all questions correctly.
4. Answered all questions correctly again.
5. Set max-attempts to 3.
6. Deleted the last node.
7. Visited the XBlock on the LMS.

The output is similar to the previous crash in that there's just a couple of buttons and no content. However I see no exception thrown in the Javascript console.

**Comment by bradenmacdonald** [comment]
@Kelketek: Good catch - the `message` node was throwing off the step count, apparently. I've just pushed a fix, along with an updated test that encompasses that situation.

**Comment by Kelketek** [comment]
:+1: Works for me, @bradenmacdonald . Thanks for being persistent on this. :)

**Comment by bradenmacdonald** [comment]
Thanks for the thorough testing, @Kelketek  :)

**Pull request merged**
