### PR TITLE
Add deprecation warning to README and link to current version

### PR DESCRIPTION
**Pull request by antoviaque**
@bradenmacdonald And a second PR, similar to https://github.com/gsehub/xblock-mentoring/pull/10 - good too?

> Updated this README to avoid people running into issues like in https://groups.google.com/forum/#!msg/edx-code/Qkrrdlhx2b8/ZhOE_zo78RIJ 

@smagoun Is this fine with you? Note that we still haven't run the migrations on the existing Yonker courses, though.

### CODE REVIEW

**Comment by smagoun** [comment]
The travis failures are concerning but since they do not appear to be related to this change, :+1:

**Comment by bradenmacdonald** [comment]
:+1: 

I think others on our team reported that the tests are passing locally. Not sure why Travis is segfaulting :-/

Another approach to this [that I've used before](https://github.com/bradenmacdonald/astrodendro) is to commit the new readme to an empty 'deprecated' branch (`git checkout --orphan deprecated`) and then configure GitHub to display the deprecated branch by default. By "removing" all the code in that way, it makes it even more obvious (for people who don't scroll down to the readme), and if people still want to access the README or the code, they can just select the master branch.

**Comment by antoviaque** [comment]
Yup, Travis regularly gives this type of headaches :/ We do make sure that the build is passing before merging code though, so this would get fixed on the next PR.

@bradenmacdonald Good idea - I'll also do that.

**Comment by antoviaque** [comment]
Done for the gsehub repo - for this repo I created the branch, but I don't have admin rights anymore. @fredsmith do you mind changing the default branch on this repo to `deprecated`?

**Pull request merged**
